config/routes.rb
Chem0parse::Application.routes.draw do

  match '/' => 'chemoinformatics#new'
  
  resources :users

  resources :chemoinformatics

end

app/models/chemoinformatic.rb
require 'rubygems'

class Chemoinformatic < ActiveRecord::Base

  def oscar_parse
    # call w nokogiri goes here
  end


end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/chemoinformatics_controller.rb
require "#{Rails.root}/lib/api.rb" # wtf is with /app/lib .. isnt it supposed to load by default?
require 'uri'
require 'net/http'


class ChemoinformaticsController < ApplicationController
  # GET /chemoinformatics
  # GET /chemoinformatics.xml
  def index
    @chemoinformatics = Chemoinformatic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @chemoinformatics }
    end
  end

  # GET /chemoinformatics/1
  # GET /chemoinformatics/1.xml
  def show
    @chemoinformatics = Chemoinformatic.all
    @chemoinformatic = Chemoinformatic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @chemoinformatic }
    end
  end

  # GET /chemoinformatics/new
  # GET /chemoinformatics/new.xml
  def new
    @chemoinformatics = Chemoinformatic.all
    @chemoinformatic = Chemoinformatic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @chemoinformatic }
    end
  end

  # GET /chemoinformatics/1/edit
  def edit
    @chemoinformatics = Chemoinformatic.all
    @chemoinformatic = Chemoinformatic.find(params[:id])
  end

  # POST /chemoinformatics
  # POST /chemoinformatics.xml
  def create
    @chemoinformatic = Chemoinformatic.new(params[:chemoinformatic])
    
    # package API call
    # verify EC2 instance is running at:
    # http://ec2-50-17-69-108.compute-1.amazonaws.com:3000/  # => Hello Hackers 3!!
    uri = URI("http://ec2-50-17-69-108.compute-1.amazonaws.com:3000/parse")
    http = Net::HTTP.new(uri.host, uri.port)
    http.read_timeout = 10 * 60 # 5 minutes
    headers = { 'Process' => @chemoinformatic.input_process }
    codified_process = []

    http.get(uri.path, headers) do |chunk|
        codified_process << chunk
    end

    puts codified_process.last
    @chemoinformatic.output_process = codified_process.last

    respond_to do |format|
      if @chemoinformatic.save
        format.html { redirect_to(@chemoinformatic, :notice => 'Chemoinformatic was successfully created.') }
        format.xml  { render :xml => @chemoinformatic, :status => :created, :location => @chemoinformatic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @chemoinformatic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chemoinformatics/1
  # PUT /chemoinformatics/1.xml
  def update
    @chemoinformatic = Chemoinformatic.find(params[:id])

    respond_to do |format|
      if @chemoinformatic.update_attributes(params[:chemoinformatic])
        format.html { redirect_to(@chemoinformatic, :notice => 'Chemoinformatic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @chemoinformatic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chemoinformatics/1
  # DELETE /chemoinformatics/1.xml
  def destroy
    @chemoinformatic = Chemoinformatic.find(params[:id])
    @chemoinformatic.destroy

    respond_to do |format|
      format.html { redirect_to(chemoinformatics_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemoinformatics_helper.rb
module ChemoinformaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chemoinformatics/_form.html.haml
= form_for(@chemoinformatic) do |f|
  - if @chemoinformatic.errors.any?
    #error_explanation
      %h2
        = pluralize(@chemoinformatic.errors.count, "error")
        prohibited this chemoinformatic from being saved:
      %ul
        - @chemoinformatic.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.text_area :input_process, :id => "chemical_process_input", :placeholder => "chemical process to be parsed"

  .actions
    = f.submit "parse", :class => "button", :disable_with => "running..."

app/views/chemoinformatics/edit.html.haml
#header_container
  #title_container.inline
    %h1{:id => "title"} chem0_Edit
    =link_to("https://bitbucket.org/wwmm/oscar4/wiki/Home", :target => "_blank") do
      %h6
        = @chemoinformatics.count 
        indexes parsed by OSCAR-4


  = link_to(chemoinformatics_path, :id => "chemo_index_link") do
    #nav_button.button.inline browse    



= render 'form'
/= link_to 'Show', @chemoinformatic
/#{link_to 'Back', chemoinformatics_path}

app/views/chemoinformatics/index.html.haml
#header_container
  #title_container.inline
    %h1{:id => "title"} chem0_Browse
    =link_to("https://bitbucket.org/wwmm/oscar4/wiki/Home", :target => "_blank") do
      %h6
        = @chemoinformatics.count 
        indexes parsed by OSCAR-4

  = link_to(new_chemoinformatic_path, :id => "chemo_index_link") do
    #nav_button.button.inline parse

  %br


%table{ :id => "display_table" }
  %tr
    %th.input_process.top-left-5 Input process
    %th Output process
    %th
    %th
    %th.top-right-5

  - @chemoinformatics.each do |chemoinformatic|
    %tr{:class=> cycle("even","odd")}
      %td= chemoinformatic.input_process
      %td
        - chemoinformatic.output_process.split("**!**").each do |line|
          = line
          %br

      %td= link_to 'Show', chemoinformatic
      %td= link_to 'Edit', edit_chemoinformatic_path(chemoinformatic)
      %td= link_to 'Destroy', chemoinformatic, :confirm => 'Are you sure?', :method => :delete

  %tr
    %th.bottom-left-5
    %th
    %th
    %th
    %th.bottom-right-5

%br/

app/views/chemoinformatics/new.html.haml
#header_container
  #title_container.inline
    %h1{:id => "title"} chem0_Parse
    =link_to("https://bitbucket.org/wwmm/oscar4/wiki/Home", :target => "_blank") do
      %h6
        = @chemoinformatics.count 
        indexes parsed by OSCAR-4


  = link_to(chemoinformatics_path, :id => "chemo_index_link") do
    #nav_button.button.inline browse    

#parse_container
  #parse_options
    .parse_option_container
      #parse_opt1.parse_box
        1
    .parse_option_container
      #parse_opt2.parse_box
        2
    .parse_option_container
      #parse_opt3.parse_box
        3
    .parse_option_container
      #parse_opt4.parse_box
        4
    .parse_option_container
      #parse_opt5.parse_box
        5
    .parse_option_container
      #parse_opt6.parse_box
        6

  = render 'form'

app/views/chemoinformatics/show.html.haml
#header_container
  #title_container.inline
    %h1{:id => "title"} chem0_view
    =link_to("https://bitbucket.org/wwmm/oscar4/wiki/Home", :target => "_blank") do
      %h6
        = @chemoinformatics.count 
        indexes parsed by OSCAR-4

  = link_to(chemoinformatics_path, :id => "chemo_index_link") do
    #nav_button.button.inline browse    

/ %p#notice= notice

%table{ :id => "display_table" }
  %tr
    %th.input_process.top-left-5
      %b Input process:
    %th.top-right-5
      %b Output process:
  %tr.odd
    %td
      = @chemoinformatic.input_process
    %td
      - @chemoinformatic.output_process.split("**!**").each do |line|
        = line
        %br


  %tr
    %th.bottom-left-5
    %th.bottom-right-5
  
%p

  
/ = link_to 'Edit', edit_chemoinformatic_path(@chemoinformatic)

/ #{link_to 'Back', chemoinformatics_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title chem0_Parser
    %link{:href => "http://fonts.googleapis.com/css?family=Economica", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag 'screen'
    = javascript_include_tag :defaults, 'application'
    = csrf_meta_tag
  %body
    #main_container
      = yield

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :email
    %br/
    = f.text_field :email
  .actions
    = f.submit

app/views/users/edit.html.haml
%h1 Editing user
= render 'form'
= link_to 'Show', @user
|
\#{link_to 'Back', users_path}

app/views/users/index.html.haml
%h1 Listing users
%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user
= render 'form'
= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
= link_to 'Edit', edit_user_path(@user)
|
\#{link_to 'Back', users_path}